host:
  api_root_url: "http://43.138.88.28:8080/woniusales"
  api_content_type: "application/x-www-form-urlencoded; charset=UTF-8"

# chrome  or firefox
browserType:
  browser_type: "chrome"

mysql:
  MYSQL_HOST: "43.138.88.28"
  MYSQL_PORT: "12345"
  MYSQL_USER: "root"
  MYSQL_PASSWD: "123456"
  MYSQL_DB: "woniusale"

